import type { ProjectContentBundle } from "@/lib/admin/types/content";

export const mockProjectContent: ProjectContentBundle = {
  cards: [
    {
      id: "project-card-01",
      title: "Nhà Phú Nhuận",
      slug: "nha-phu-nhuan",
      thumbnail: "/images/projects/project-01.png",
      imageAlt: "Dự án nhà ở tại Phú Nhuận",
      category: "Nhà ở",
      href: "/du-an/nha-phu-nhuan",
      status: "published",
      order: 1,
      createdAt: "18/08/2026",
    },
    {
      id: "project-card-02",
      title: "Nhà Bình Thạnh",
      slug: "nha-binh-thanh",
      thumbnail: "/images/projects/project-02.png",
      imageAlt: "Dự án nhà ở tại Bình Thạnh",
      category: "Nhà ở",
      href: "/du-an/nha-binh-thanh",
      status: "published",
      order: 2,
      createdAt: "16/08/2026",
    },
    {
      id: "project-card-03",
      title: "Văn phòng BMT Decor",
      slug: "van-phong-bmt-decor",
      thumbnail: "/images/projects/project-03.png",
      imageAlt: "Không gian văn phòng BMT Decor",
      category: "Văn phòng",
      href: "/du-an/van-phong-bmt-decor",
      status: "draft",
      order: 3,
      createdAt: "14/08/2026",
    },
    {
      id: "project-card-04",
      title: "Showroom nội thất BMT",
      slug: "showroom-noi-that-bmt",
      thumbnail: "/images/projects/project-04.png",
      imageAlt: "Showroom nội thất BMT Decor",
      category: "Thẩm mỹ viện, showroom",
      href: "/du-an/showroom-noi-that-bmt",
      status: "published",
      order: 4,
      createdAt: "12/08/2026",
    },
    {
      id: "project-card-05",
      title: "Nhà hàng sân vườn Thủ Đức",
      slug: "nha-hang-san-vuon-thu-duc",
      thumbnail: "/images/projects/project-05.png",
      imageAlt: "Nhà hàng sân vườn tại Thủ Đức",
      category: "Nhà hàng, khách sạn",
      href: "/du-an/nha-hang-san-vuon-thu-duc",
      status: "published",
      order: 5,
      createdAt: "10/08/2026",
    },
    {
      id: "project-card-06",
      title: "Nhà phố 2 tầng Quận 9",
      slug: "nha-pho-2-tang-quan-9",
      thumbnail: "/images/projects/project-06.png",
      imageAlt: "Nhà phố 2 tầng tại Quận 9",
      category: "Nhà ở",
      href: "/du-an/nha-pho-2-tang-quan-9",
      status: "published",
      order: 6,
      createdAt: "08/08/2026",
    },
    {
      id: "project-card-07",
      title: "Studio sáng tạo Phú Nhuận",
      slug: "studio-sang-tao-phu-nhuan",
      thumbnail: "/images/projects/project-07.png",
      imageAlt: "Studio sáng tạo tại Phú Nhuận",
      category: "Văn phòng",
      href: "/du-an/studio-sang-tao-phu-nhuan",
      status: "draft",
      order: 7,
      createdAt: "06/08/2026",
    },
    {
      id: "project-card-08",
      title: "Spa chăm sóc da Phú Nhuận",
      slug: "spa-cham-soc-da-phu-nhuan",
      thumbnail: "/images/projects/project-08.png",
      imageAlt: "Spa chăm sóc da tại Phú Nhuận",
      category: "Thẩm mỹ viện, showroom",
      href: "/du-an/spa-cham-soc-da-phu-nhuan",
      status: "draft",
      order: 8,
      createdAt: "04/08/2026",
    },
  ],
  categories: [
    {
      id: "category-house",
      label: "Nhà ở",
      icon: "/images/projects/category-house-active.png",
      activeIcon: "/images/projects/category-house-active.png",
      mobileIcon: "/images/projects/mobile/category-house.png",
      mobileActiveIcon: "/images/projects/mobile/category-house-active.png",
      order: 1,
    },
    {
      id: "category-office",
      label: "Văn phòng",
      icon: "/images/projects/category-office.png",
      activeIcon: "/images/projects/category-office-active.png",
      mobileIcon: "/images/projects/mobile/category-office.png",
      mobileActiveIcon: "/images/projects/mobile/category-office-active.png",
      order: 2,
    },
    {
      id: "category-showroom",
      label: "Thẩm mỹ viện, showroom",
      icon: "/images/projects/category-showroom.png",
      activeIcon: "/images/projects/category-showroom-active.png",
      mobileIcon: "/images/projects/mobile/category-showroom.png",
      mobileActiveIcon: "/images/projects/mobile/category-showroom-active.png",
      order: 3,
    },
    {
      id: "category-hospitality",
      label: "Nhà hàng, khách sạn",
      icon: "/images/projects/category-hospitality.png",
      activeIcon: "/images/projects/category-hospitality-active.png",
      mobileIcon: "/images/projects/mobile/category-hospitality.png",
      mobileActiveIcon:
        "/images/projects/mobile/category-hospitality-active.png",
      order: 4,
    },
  ],
  details: [
    {
      id: "project-detail-moc-mien",
      slug: "nha-pho-2-tang-quan-9",
      title: "Mộc Miên House",
      category: "Nhà phố",
      location: "Quận 9, TP.HCM (cũ)",
      client: "Anh Nhân",
      area: "210m²",
      scale: "2 tầng + tum",
      styleText: "Wabi Sabi",
      scope: "Thiết kế và thi công trọn gói",
      year: 2026,
      overview:
        "Không gian sống đơn giản, mộc mạc, gọn gàng và tối ưu công năng cho nhu cầu sinh hoạt hằng ngày.",
      surveyText:
        "Hiện trạng có diện tích tốt nhưng cách bố trí nội thất chưa tối ưu, ánh sáng tự nhiên còn hạn chế.",
      drawingCaption: "Bản vẽ mặt bằng bố trí",
      solution:
        "Phương án cải tạo sử dụng các đường bo cong nhẹ, khoảng đặc rỗng cân đối và vật liệu có bề mặt tự nhiên.",
      processDescription:
        "Đội ngũ triển khai từ khảo sát, xử lý hiện trạng đến thi công hoàn thiện theo quy trình kiểm soát chất lượng.",
      heroImage: "/images/projects/detail/project-cover.png",
      heroAlt: "Mặt tiền hoàn thiện của Mộc Miên House về đêm",
    },
  ],
  related: [
    {
      id: "related-01",
      title: "Chung cư La Astoria Q.2",
      image: "/images/projects/project-03.png",
      imageAlt: "Chung cư La Astoria Quận 2",
      href: "/du-an/nha-pho-2-tang-quan-9",
      order: 1,
    },
    {
      id: "related-02",
      title: "Căn hộ The Opera Residence",
      image: "/images/projects/project-05.png",
      imageAlt: "Căn hộ The Opera Residence",
      href: "/du-an/nha-pho-2-tang-quan-9",
      order: 2,
    },
    {
      id: "related-03",
      title: "Nhà phố Bình Chánh",
      image: "/images/projects/project-07.png",
      imageAlt: "Nhà phố tại Bình Chánh",
      href: "/du-an/nha-pho-2-tang-quan-9",
      order: 3,
    },
    {
      id: "related-04",
      title: "Căn hộ chung cư Q7",
      image: "/images/projects/project-09.png",
      imageAlt: "Căn hộ chung cư Quận 7",
      href: "/du-an/nha-pho-2-tang-quan-9",
      order: 4,
    },
  ],
};
